import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { openDashboard, nodes } from './fixtures.js'

async function openWorkspace(page) {
  await page.getByTestId('investigations').locator(':scope > summary').click()
}
async function finish(page, summary = { avg_ms: 10, loss_pct: 0 }, output = 'Reply from example.com') {
  await page.evaluate(({ summary, output }) => {
    const id = window.sent.findLast((message) => message.command).command.id
    const socket = window.sockets.findLast((item) => String(item.url).includes('/ws/client'))
    socket.emit({ id, type: 'output', data: output })
    socket.emit({ id, type: 'summary', data: JSON.stringify(summary) })
    socket.emit({ id, type: 'done', data: '{"exit_ok":true}' })
  }, { summary, output })
}
async function runPing(page, summary) {
  await page.getByLabel('Command target', { exact: true }).fill('example.com')
  await page.getByRole('button', { name: 'Run', exact: true }).first().click()
  await finish(page, summary)
  await expect(page.getByRole('button', { name: 'Stop', exact: true })).not.toBeVisible()
}

test('explicit baselines persist, compare like-for-like, expire and delete', async ({ context }) => {
  const page = await openDashboard(context)
  await runPing(page, { avg_ms: 10, loss_pct: 0 })
  expect(await page.evaluate(() => localStorage.getItem('lg-baselines-v1'))).toBeNull()
  await openWorkspace(page)
  await page.getByRole('button', { name: 'Save baseline', exact: true }).click()
  const id = await page.evaluate(() => JSON.parse(localStorage.getItem('lg-baselines-v1'))[0].id)
  await page.getByLabel('Saved baseline', { exact: true }).selectOption(id)
  await runPing(page, { avg_ms: 20, loss_pct: 25 })
  await expect(page.getByLabel('Baseline comparison')).toContainText('+10 ms')
  await expect(page.getByLabel('Baseline comparison')).toContainText('+25 percentage points')
  await page.getByRole('button', { name: /^Selected node:/ }).click()
  await page.getByRole('button', { name: 'Node B, Site 2, online', exact: true }).click()
  await runPing(page)
  await expect(page.getByText('Choose results with the same node name, location, command, target and options.', { exact: false })).toBeVisible()
  await page.reload()
  await openWorkspace(page)
  await expect(page.getByLabel('Saved baseline', { exact: true }).locator('option')).toHaveCount(2)
  await page.getByLabel('Saved baseline', { exact: true }).selectOption(id)
  await page.getByRole('button', { name: 'Delete selected baseline', exact: true }).click()
  expect(await page.evaluate(() => localStorage.getItem('lg-baselines-v1'))).toBeNull()
  await runPing(page)
  await page.getByRole('button', { name: 'Save baseline', exact: true }).click()
  await page.evaluate(() => { const entries = JSON.parse(localStorage.getItem('lg-baselines-v1')); entries[0].expiresAt = Date.now() - 1; localStorage.setItem('lg-baselines-v1', JSON.stringify(entries)) })
  await page.reload()
  expect(await page.evaluate(() => localStorage.getItem('lg-baselines-v1'))).toBeNull()
  expect(page.errors).toEqual([])
})

test('guided checks advance through failures, ignore retired IDs and collect observations', async ({ context }) => {
  const page = await openDashboard(context)
  await openWorkspace(page)
  await page.getByLabel('Diagnostic node', { exact: true }).selectOption('a')
  await page.getByLabel('Diagnostic hostname', { exact: true }).fill('example.com')
  await page.getByRole('button', { name: 'Run guided checks', exact: true }).click()
  const first = await page.evaluate(() => window.sent.findLast((message) => message.command).command.id)
  await finish(page, { answer_count: 1, status: 'NOERROR' }, 'DNS answer 192.0.2.1')
  await expect.poll(() => page.evaluate(() => window.sent.filter((message) => message.command).length)).toBe(2)
  await page.evaluate((id) => { window.sockets.at(-1).emit({ id, type: 'done', data: '' }); window.sockets.at(-1).emit({ id, type: 'output', data: 'STALE OUTPUT' }) }, first)
  expect(await page.evaluate(() => window.sent.filter((message) => message.command).length)).toBe(2)
  await page.evaluate(() => { const id = window.sent.findLast((message) => message.command).command.id; window.sockets.at(-1).emit({ id, type: 'error', data: 'TCP refused' }); window.sockets.at(-1).emit({ id, type: 'done', data: '{"exit_ok":false}' }) })
  await finish(page, { chain_ok: false }, 'Invalid certificate chain')
  await finish(page, { http_code: 503 }, 'Service unavailable')
  await expect(page.getByText('Checks finished. Review the observations below.')).toBeVisible()
  expect(await page.evaluate(() => window.sent.filter((message) => message.command).map((message) => message.command.type))).toEqual(['dns', 'tcp', 'tls', 'http'])
  await expect(page.getByTestId('investigations')).toContainText('certificate chain was not trusted')
  await page.getByRole('button', { name: 'Add guided results to incident', exact: true }).click()
  await expect(page.getByText('4/20 checks collected')).toBeVisible()
  await page.getByRole('button', { name: 'Preview incident report', exact: true }).click()
  const preview = await page.getByLabel('Incident report preview', { exact: true }).inputValue()
  expect(preview).toContain('TCP refused')
  expect(preview).toContain('HTTP 503')
  expect(preview).not.toContain('STALE OUTPUT')
  expect(page.errors).toEqual([])
})

for (const interrupt of ['cancel', 'disconnect']) {
  test(`guided ${interrupt} stops the sequence and retains an explicitly incomplete result`, async ({ context }) => {
    const page = await openDashboard(context)
    await openWorkspace(page)
    await page.getByLabel('Diagnostic node', { exact: true }).selectOption('a')
    await page.getByLabel('Diagnostic hostname', { exact: true }).fill('example.com')
    await page.getByRole('button', { name: 'Run guided checks', exact: true }).click()
    if (interrupt === 'cancel') await page.getByRole('button', { name: 'Stop guided checks', exact: true }).click()
    else await page.evaluate(() => window.sockets.at(-1).close())
    await page.evaluate(() => { const id = window.sent.find((message) => message.command).command.id; window.sockets.at(-1).emit({ id, type: 'done', data: '' }) })
    expect(await page.evaluate(() => window.sent.filter((message) => message.command).length)).toBe(1)
    await expect(page.getByRole('button', { name: 'Add guided results to incident', exact: true })).toBeEnabled()
    await expect(page.getByTestId('investigations')).toContainText('failed or was interrupted')
    expect(page.errors).toEqual([])
  })
}

test('incident report freezes collected results and downloads exactly the redacted preview', async ({ context }) => {
  const page = await openDashboard(context)
  await runPing(page)
  await openWorkspace(page)
  await page.getByRole('button', { name: 'Add current result to incident', exact: true }).click()
  await page.getByRole('button', { name: /^Selected node:/ }).click()
  await page.getByRole('button', { name: 'Node B, Site 2, online', exact: true }).click()
  await runPing(page)
  await page.getByRole('button', { name: 'Add current result to incident', exact: true }).click()
  await page.getByLabel('Report title', { exact: true }).fill('example.com investigation')
  await page.getByRole('button', { name: 'Preview incident report', exact: true }).click()
  await page.getByRole('button', { name: 'Remove check 1', exact: true }).click()
  await page.getByLabel('Redact incident text', { exact: true }).fill('example.com\nNode A\nNode B')
  const preview = await page.getByLabel('Incident report preview', { exact: true }).inputValue()
  expect(preview).not.toContain('example.com')
  expect(preview).not.toContain('Node A')
  expect(preview).toContain('Check 2')
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download incident report', exact: true }).click()
  const download = await pending
  const stream = await download.createReadStream(), chunks = []
  for await (const chunk of stream) chunks.push(chunk)
  expect(Buffer.concat(chunks).toString()).toBe(preview)
  await page.getByRole('button', { name: 'Clear incident draft', exact: true }).click()
  await expect(page.getByLabel('Incident report preview', { exact: true })).not.toBeVisible()
  await expect(page.getByText('0/20 checks collected')).toBeVisible()
  expect(page.errors).toEqual([])
})

test('readiness distinguishes version differences, missing probes and legacy unknown capabilities', async ({ context }) => {
  const page = await openDashboard(context, { nodes: [{ ...nodes[0], version: 'v1.0', tools: { ping: true, dns: false } }, { ...nodes[1], version: 'v2.0', tools: {} }] })
  await page.getByTitle('Node health overview', { exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Node health overview' })
  await expect(dialog).toContainText('2 reported builds')
  await dialog.getByLabel('Expected version (optional)', { exact: true }).fill('v2.0')
  const rows = dialog.getByTestId('agent-readiness')
  await expect(rows.nth(0)).toContainText('Different from expected version')
  await expect(rows.nth(1)).toContainText('Matches expected version')
  await dialog.getByLabel('Required diagnostic', { exact: true }).selectOption('tls')
  await expect(rows.nth(0)).toContainText('tls: Unavailable')
  await expect(rows.nth(1)).toContainText('tls: Unknown')
  await dialog.getByLabel('Required diagnostic', { exact: true }).selectOption('dns')
  await expect(rows.nth(0)).toContainText('dns is not installed')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await openWorkspace(page)
  await page.getByLabel('Diagnostic node', { exact: true }).selectOption('a')
  await page.getByLabel('Diagnostic hostname', { exact: true }).fill('example.com')
  await expect(page.getByRole('button', { name: 'Run guided checks', exact: true })).toBeDisabled()
  await page.getByLabel('Diagnostic symptom', { exact: true }).selectOption('dns')
  await expect(page.getByTestId('investigations').getByText('dns is not installed on this node', { exact: true })).toHaveCount(1)
  expect(page.errors).toEqual([])
})

test('workspace is accessible on mobile and unavailable to public sessions', async ({ context }) => {
  const page = await openDashboard(context)
  await page.setViewportSize({ width: 390, height: 844 })
  await openWorkspace(page)
  await page.getByLabel('Diagnostic node', { exact: true }).selectOption('a')
  await page.getByLabel('Diagnostic hostname', { exact: true }).fill('example.com')
  const scan = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(scan.violations).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const publicPage = await openDashboard(context, { publicMode: true, commands: ['ping'], targets: ['example.com'] })
  await expect(publicPage.getByTestId('investigations')).toHaveCount(0)
})

test('blocked baseline storage is reported and incident drafts still work', async ({ context }) => {
  const page = await openDashboard(context, { blockStorage: true })
  await runPing(page)
  await openWorkspace(page)
  await page.getByRole('button', { name: 'Save baseline', exact: true }).click()
  await expect(page.getByTestId('investigations')).toContainText('Couldn’t save baseline')
  await page.getByRole('button', { name: 'Add current result to incident', exact: true }).click()
  await expect(page.getByText('1/20 checks collected')).toBeVisible()
  expect(page.errors).toEqual([])
})

test('multi-node results enter a report with captured metadata and interrupted checks marked', async ({ context }) => {
  const page = await openDashboard(context)
  await page.getByTitle('Multi-node comparison', { exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Multi-Node Comparison' })
  await dialog.getByRole('button', { name: /Node A/ }).click()
  await dialog.getByRole('button', { name: /Node B/ }).click()
  await dialog.getByLabel('Comparison target', { exact: true }).fill('example.com')
  await dialog.getByRole('button', { name: 'Run All', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Add comparison to incident', exact: true })).toBeDisabled()
  await page.evaluate(() => {
    const commands = window.sent.filter((message) => message.command)
    for (const item of commands) window.sockets.at(-1).emit({ id: item.command.id, type: 'output', data: `${item.node_id}: synthetic observation` })
    const first = commands[0].command.id
    window.sockets.at(-1).emit({ id: first, type: 'done', data: '{"exit_ok":true}' })
  })
  await dialog.getByRole('button', { name: /Stop/ }).click()
  await dialog.getByRole('button', { name: 'Add comparison to incident', exact: true }).click()
  await page.keyboard.press('Escape')
  await openWorkspace(page)
  await expect(page.getByText('2/20 checks collected')).toBeVisible()
  await page.getByRole('button', { name: 'Preview incident report', exact: true }).click()
  const preview = await page.getByLabel('Incident report preview', { exact: true }).inputValue()
  expect(preview).toContain('Node: Node A')
  expect(preview).toContain('Node: Node B')
  expect(preview).toContain('example.com')
  expect(preview).toContain('Result incomplete')
  expect(page.errors).toEqual([])
})

test('guided timeout stops further commands and records the interruption', async ({ context }) => {
  const page = await openDashboard(context)
  await page.clock.install()
  await openWorkspace(page)
  await page.getByLabel('Diagnostic node', { exact: true }).selectOption('a')
  await page.getByLabel('Diagnostic hostname', { exact: true }).fill('example.com')
  await page.getByRole('button', { name: 'Run guided checks', exact: true }).click()
  await page.clock.fastForward(616000)
  await expect(page.getByText('Check timed out; remaining checks were stopped.', { exact: true }).first()).toBeVisible()
  expect(await page.evaluate(() => window.sent.filter((message) => message.command).length)).toBe(1)
  expect(await page.evaluate(() => window.sent.some((message) => message.action === 'cancel'))).toBe(true)
})
